{
 "title": "MariaDB healthcheck",
 "description": "MariaDB dashboard using ElasticSearch, metricbeat with mysql and sql (sql_response_format=table) modules.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": "{\"find\": \"terms\", \"field\": \"fields.mariadb.env\" }"
   },
   {
    "name": "hostname",
    "label": "hostname",
    "query": "{\"find\": \"terms\", \"field\": \"fields.mariadb.alias\",\"query\": \"fields.mariadb.env: $env\"}"
   },
   {
    "name": "database",
    "label": "database",
    "query": "{\"find\": \"terms\", \"field\": \"sql.metrics.string.db\",\"query\": \"fields.mariadb.alias: $hostname\"}"
   }
  ]
 },
 "panels": [
  { "title": "MariaDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:546",
       "field": "@timestamp",
       "id": "1",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:544", "field": "sql.metrics.numeric.value", "id": "1", "type": "max" }
     ],
     "query": "fields.mariadb.alias: $hostname and sql.metrics.string.variable_name: 'Uptime'\r and fields.mariadb.env: $env",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Open Sessions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Connected",
     "bucketAggs": [
      {
       "$$hashKey": "object:820",
       "field": "@timestamp",
       "id": "1",
       "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:818", "field": "mysql.status.threads.connected", "id": "1", "type": "avg" }
     ],
     "query": "fields.mariadb.alias: $hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Running",
     "bucketAggs": [
      {
       "$$hashKey": "object:771",
       "field": "@timestamp",
       "id": "1",
       "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:769", "field": "mysql.status.threads.running", "id": "1", "type": "avg" }
     ],
     "query": "fields.mariadb.alias: $hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Cached",
     "bucketAggs": [
      {
       "$$hashKey": "object:91",
       "field": "@timestamp",
       "id": "1",
       "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:89", "field": "mysql.status.threads.cached", "id": "1", "type": "avg" }
     ],
     "query": "fields.mariadb.alias: $hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "Created",
     "bucketAggs": [
      {
       "$$hashKey": "object:99",
       "field": "@timestamp",
       "id": "1",
       "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:97", "field": "mysql.status.threads.created", "id": "1", "type": "avg" }
     ],
     "query": "fields.mariadb.alias: $hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Database time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database time (command|state)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:1490",
         "fake": true,
         "field": "sql.metrics.string.command",
         "id": "5",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:147",
         "field": "sql.metrics.string.state",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:148",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "0", "offset": "10s", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:145", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "fields.mariadb.alias: $hostname  AND sql.metrics.string.db: $database AND NOT sql.metrics.string.command: Sleep",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Database usage and cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Commands",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Delete",
       "bucketAggs": [
        {
         "$$hashKey": "object:406",
         "field": "@timestamp",
         "id": "1",
         "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:402",
         "field": "mysql.status.command.delete",
         "hide": true,
         "id": "1",
         "type": "avg"
        },
        {
         "$$hashKey": "object:403",
         "field": "1",
         "id": "2",
         "pipelineAgg": "1",
         "type": "derivative"
        }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      },
      {
       "alias": "Insert",
       "bucketAggs": [
        {
         "$$hashKey": "object:412",
         "field": "@timestamp",
         "id": "1",
         "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:408",
         "field": "mysql.status.command.insert",
         "hide": true,
         "id": "1",
         "type": "avg"
        },
        {
         "$$hashKey": "object:409",
         "field": "1",
         "id": "2",
         "pipelineAgg": "1",
         "type": "derivative"
        }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      },
      {
       "alias": "Select",
       "bucketAggs": [
        {
         "$$hashKey": "object:418",
         "field": "@timestamp",
         "id": "1",
         "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:414",
         "field": "mysql.status.command.select",
         "hide": true,
         "id": "1",
         "type": "avg"
        },
        {
         "$$hashKey": "object:415",
         "field": "1",
         "id": "2",
         "pipelineAgg": "1",
         "type": "derivative"
        }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      },
      {
       "alias": "Update",
       "bucketAggs": [
        {
         "$$hashKey": "object:424",
         "field": "@timestamp",
         "id": "1",
         "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:420",
         "field": "mysql.status.command.update",
         "hide": true,
         "id": "1",
         "type": "avg"
        },
        { "$$hashKey": "object:421", "id": "2", "type": "derivative" }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Cache",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Hits",
       "bucketAggs": [
        {
         "$$hashKey": "object:270",
         "field": "@timestamp",
         "id": "1",
         "settings": { "interval": "10m", "min_doc_count": "0", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:268",
         "field": "mysql.status.cache.table.open_cache.hits",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      },
      {
       "alias": "Misses",
       "bucketAggs": [
        {
         "$$hashKey": "object:274",
         "field": "@timestamp",
         "id": "1",
         "settings": { "interval": "10m", "min_doc_count": "0", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:272",
         "field": "mysql.status.cache.table.open_cache.misses",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      },
      {
       "alias": "Overflows",
       "bucketAggs": [
        {
         "$$hashKey": "object:278",
         "field": "@timestamp",
         "id": "1",
         "settings": { "interval": "10m", "min_doc_count": "0", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:276",
         "field": "mysql.status.cache.table.open_cache.overflows",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Binlog",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "cache disk_use",
       "bucketAggs": [
        { "field": "@timestamp", "id": "1", "settings": { "interval": "10m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.binlog.cache.disk_use",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      },
      {
       "alias": "cache use",
       "bucketAggs": [
        { "field": "@timestamp", "id": "1", "settings": { "interval": "10m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.binlog.cache.use", "id": "1", "type": "avg" }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Network and Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Send/Received",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Bytes Sent",
       "bucketAggs": [
        { "field": "@timestamp", "id": "1", "settings": { "interval": "30s", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.bytes.sent",
         "hide": true,
         "id": "1",
         "type": "max"
        },
        { "field": "1", "id": "2", "pipelineAgg": "1", "type": "derivative" }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      },
      {
       "alias": "Bytes Received",
       "bucketAggs": [
        { "field": "@timestamp", "id": "1", "settings": { "interval": "30s", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.bytes.received",
         "hide": true,
         "id": "1",
         "type": "avg"
        },
        { "field": "1", "id": "2", "pipelineAgg": "1", "type": "derivative" }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Connection Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 9, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "accept",
       "bucketAggs": [
        { "field": "@timestamp", "id": "1", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.connection.errors.accept",
         "hide": true,
         "id": "1",
         "type": "avg"
        },
        { "field": "1", "id": "2", "pipelineAgg": "1", "type": "derivative" }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      },
      {
       "alias": "internal",
       "bucketAggs": [
        { "field": "@timestamp", "id": "1", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.connection.errors.internal",
         "hide": true,
         "id": "1",
         "type": "avg"
        },
        { "field": "1", "id": "2", "pipelineAgg": "1", "type": "derivative" }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      },
      {
       "alias": "max",
       "bucketAggs": [
        { "field": "@timestamp", "id": "1", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.connection.errors.max",
         "hide": true,
         "id": "1",
         "type": "avg"
        },
        { "field": "1", "id": "2", "pipelineAgg": "1", "type": "derivative" }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      },
      {
       "alias": "peer_address",
       "bucketAggs": [
        { "field": "@timestamp", "id": "1", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.connection.errors.peer_address",
         "hide": true,
         "id": "1",
         "type": "avg"
        },
        { "field": "1", "id": "2", "pipelineAgg": "1", "type": "derivative" }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      },
      {
       "alias": "select",
       "bucketAggs": [
        { "field": "@timestamp", "id": "1", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.connection.errors.select",
         "hide": true,
         "id": "1",
         "type": "avg"
        },
        { "field": "1", "id": "2", "pipelineAgg": "1", "type": "derivative" }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      },
      {
       "alias": "tcpwrap",
       "bucketAggs": [
        { "field": "@timestamp", "id": "1", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.connection.errors.tcpwrap",
         "hide": true,
         "id": "1",
         "type": "avg"
        },
        { "field": "1", "id": "2", "pipelineAgg": "1", "type": "derivative" }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Aborted Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Clients",
       "bucketAggs": [
        { "field": "@timestamp", "id": "1", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.aborted.clients",
         "hide": true,
         "id": "1",
         "type": "avg"
        },
        { "field": "1", "id": "2", "pipelineAgg": "1", "type": "derivative" }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      },
      {
       "alias": "Connects",
       "bucketAggs": [
        { "field": "@timestamp", "id": "1", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.aborted.connects",
         "hide": true,
         "id": "1",
         "type": "avg"
        },
        { "field": "1", "id": "2", "pipelineAgg": "1", "type": "derivative" }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "InnoDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "InnoDB.BufferPool Data",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "alias": "Data",
       "bucketAggs": [
        { "field": "@timestamp", "id": "1", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.innodb.buffer_pool.bytes.data",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "InnoDB.BufferPool Pages",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 4, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Data",
       "bucketAggs": [
        {
         "$$hashKey": "object:43",
         "field": "@timestamp",
         "id": "1",
         "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:39",
         "field": "mysql.status.innodb.buffer_pool.pages.data",
         "hide": true,
         "id": "1",
         "type": "avg"
        },
        {
         "$$hashKey": "object:40",
         "field": "1",
         "id": "2",
         "pipelineAgg": "1",
         "type": "derivative"
        }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      },
      {
       "alias": "Dirty",
       "bucketAggs": [
        {
         "$$hashKey": "object:49",
         "field": "@timestamp",
         "id": "1",
         "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:45",
         "field": "mysql.status.innodb.buffer_pool.pages.dirty",
         "hide": true,
         "id": "1",
         "type": "avg"
        },
        {
         "$$hashKey": "object:46",
         "field": "1",
         "id": "2",
         "pipelineAgg": "1",
         "type": "derivative"
        }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      },
      {
       "alias": "Flushed",
       "bucketAggs": [
        {
         "$$hashKey": "object:55",
         "field": "@timestamp",
         "id": "1",
         "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:51",
         "field": "mysql.status.innodb.buffer_pool.pages.flushed",
         "hide": true,
         "id": "1",
         "type": "avg"
        },
        {
         "$$hashKey": "object:52",
         "field": "1",
         "id": "2",
         "pipelineAgg": "1",
         "type": "derivative"
        }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      },
      {
       "alias": "Free",
       "bucketAggs": [
        {
         "$$hashKey": "object:61",
         "field": "@timestamp",
         "id": "1",
         "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:57",
         "field": "mysql.status.innodb.buffer_pool.pages.free",
         "hide": true,
         "id": "1",
         "type": "avg"
        },
        {
         "$$hashKey": "object:58",
         "field": "1",
         "id": "2",
         "pipelineAgg": "1",
         "type": "derivative"
        }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      },
      {
       "alias": "Latched",
       "bucketAggs": [
        {
         "$$hashKey": "object:67",
         "field": "@timestamp",
         "id": "1",
         "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:63",
         "field": "mysql.status.innodb.buffer_pool.pages.latched",
         "hide": true,
         "id": "1",
         "type": "avg"
        },
        {
         "$$hashKey": "object:64",
         "field": "1",
         "id": "2",
         "pipelineAgg": "1",
         "type": "derivative"
        }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      },
      {
       "alias": "Misc",
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "field": "@timestamp",
         "id": "1",
         "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:69",
         "field": "mysql.status.innodb.buffer_pool.pages.misc",
         "hide": true,
         "id": "1",
         "type": "avg"
        },
        {
         "$$hashKey": "object:70",
         "field": "1",
         "id": "2",
         "pipelineAgg": "1",
         "type": "derivative"
        }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "InnoDB.rows Read",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 9, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "reads",
       "bucketAggs": [
        {
         "$$hashKey": "object:716",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:714",
         "field": "mysql.status.innodb.rows.reads",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "$$hashKey": "object:732",
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      },
      {
       "alias": "updated",
       "bucketAggs": [
        {
         "$$hashKey": "object:716",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:714",
         "field": "mysql.status.innodb.rows.updated",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "$$hashKey": "object:732",
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      },
      {
       "alias": "inserted",
       "bucketAggs": [
        {
         "$$hashKey": "object:716",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:714",
         "field": "mysql.status.innodb.rows.inserted",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "$$hashKey": "object:732",
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      },
      {
       "alias": "deleted",
       "bucketAggs": [
        {
         "$$hashKey": "object:716",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:714",
         "field": "mysql.status.innodb.rows.del",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "$$hashKey": "object:732",
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "InnoDB.rows",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Deleted",
       "bucketAggs": [
        { "field": "@timestamp", "id": "1", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.innodb.rows.deleted",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      },
      {
       "alias": "Inserted",
       "bucketAggs": [
        { "field": "@timestamp", "id": "1", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.innodb.rows.inserted",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      },
      {
       "alias": "Updates",
       "bucketAggs": [
        { "field": "@timestamp", "id": "1", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.innodb.rows.updated",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Instance Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "by User",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:175",
         "fake": true,
         "field": "sql.metrics.string.user",
         "id": "3",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:41",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": 0, "offset": "10s", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:39", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "fields.mariadb.alias: $hostname AND sql.metrics.string.db: $database NOT sql.metrics.string.command: Sleep",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Instance Time by Query",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:175",
         "fake": true,
         "field": "sql.metrics.string.info",
         "id": "3",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:41",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:39", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "fields.mariadb.alias: $hostname AND sql.metrics.string.user: /[a-z]*/ AND sql.metrics.string.db: $database AND NOT sql.metrics.string.command: Sleep",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Memory by query",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:1118",
         "fake": true,
         "field": "sql.metrics.string.info",
         "id": "3",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:41",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:39",
         "field": "sql.metrics.numeric.memory_used",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "fields.mariadb.alias: $hostname",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "ProcessList",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "User Sessions",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:238",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:236",
         "field": "select field",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "logs"
        }
       ],
       "query": "fields.mariadb.alias: $hostname AND sql.metrics.string.user: /[a-z]*/ AND sql.metrics.string.db: $database AND NOT sql.metrics.string.command: Sleep",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}